// Generated by CoffeeScript 1.10.0
(function() {
  var Browserify, coffeescript_helpers, debug, pkg;

  coffeescript_helpers = require('coffeescript-helpers');

  Browserify = require('./browserify-string');

  pkg = require('./package');

  debug = (require('debug'))(pkg.name + ":browserify");

  module.exports = function(arg) {
    var browserify, context, minify, root, route;
    route = arg.route, root = arg.root, minify = arg.minify, context = arg.context;
    return browserify = function(k, v) {
      var actual, js;
      actual = coffeescript_helpers.p_exec(v);
      js = Browserify(actual, {
        basedir: root,
        paths: [root]
      }).bundle(function(err, src) {
        var ref;
        if (err) {
          debug("browserify: " + ((ref = err.stack) != null ? ref : err), actual);
          return;
        }
        js = src.toString();
        if (context.app.settings['minify']) {
          js = minify(js);
        }
        return route({
          verb: 'get',
          path: k,
          handler: js,
          type: 'js'
        });
      });
    };
  };

}).call(this);
