// Generated by CoffeeScript 1.10.0
(function() {
  var Readable, browserify, path;

  browserify = require('browserify');

  path = require('path');

  Readable = require('stream').Readable;

  module.exports = function(str, opts) {
    var stream;
    if (typeof str === 'function') {
      str = ['(', str.toString(), ')();'].join('\n');
    }
    if (opts.basedir == null) {
      opts.basedir = process.cwd();
    }
    stream = new Readable();
    stream.push(str);
    stream.push(null);
    return browserify(stream, opts);
  };

}).call(this);
