// Generated by CoffeeScript 1.10.0
(function() {
  var invariate, zappajs_plugin_client;

  invariate = require('invariate');

  module.exports = zappajs_plugin_client = function() {
    var browserify, context;
    context = this.context, browserify = this.browserify;
    return context.client = invariate(function(k, v) {
      v = "function() {\nrequire('zappajs-plugin-client').client( function(){\n  this.ready(\n    " + v + "\n  )\n})\n}";
      return browserify(k, v);
    });
  };

  module.exports.client = function() {
    return (require('zappajs-client')).apply(this, arguments);
  };

}).call(this);
